# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_QCOM)	+= apq8016-sbc.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= apq8096-db820c.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= ipq8074-hk01.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8916-mtp.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8992-bullhead-rev-101.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8994-angler-rev-101.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8996-mtp.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= sdm845-mtp.dtb

dtb-$(CONFIG_ARCH_QCOM)	+= tbj606-bengal.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= tbj606-bengalp.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= tbj606-scuba-2gb.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= tbj606-scuba-iot-2gb.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= tbj606-scuba.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= tbj606-scuba-iot.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= tbj606-scubap-iot-idp-2gb.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= tbj606-scubap.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= tbj606-scubap-iot.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= tbj606-scubap-iot-idp.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= tbj606-mpdata.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files    := *.dtb *.dtbo
